### ISSUE TITLE
pytorch implementation of the paper

### ISSUE THREAD

**Issue by yhs0602** [LiuZeJie97/Code-Generation-From-Flowcharts-with-Texts-A-Benchmark-Dataset-and-An-Approach#1]
Hello, I read your paper with title "Code Generation From Flowcharts with Texts: A Benchmark Dataset and An Approach".

Could/Do you provide the implementation (like pytorch or tensorflow) of your model?

Thank you.

**Comment by LiuZeJie97** [comment]
Thanks for your interest in our paper, the code will be released on github in two weeks. In addition, can I ask where you found our paper, considering our paper is not available on arxiv right now?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiuZeJie97/Code-Generation-From-Flowcharts-with-Texts-A-Benchmark-Dataset-and-An-Approach"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月11日(星期三) 中午1:57
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[LiuZeJie97/Code-Generation-From-Flowcharts-with-Texts-A-Benchmark-Dataset-and-An-Approach] pytorch implementation of the paper (Issue #1)





 
Hello, I read your paper with title "Code Generation From Flowcharts with Texts: A Benchmark Dataset and An Approach".
 
Could/Do you provide the implementation (like pytorch or tensorflow) of your model?
 
Thank you.

**Comment by yhs0602** [comment]
Thank you for your reply! We are studying how to generate code from natural language at Seoul National University in Korea, and our team leader found your paper here: https://huggingface.co/spaces/malteos/emnlp2022-papers
Then he googled to retrieve the content here: https://preview.aclanthology.org/emnlp-22-ingestion/volumes/2022.findings-emnlp/

**Comment by LiuZeJie97** [comment]
All codes have been released. If you have any difficulty using them, please feel free to contact us!
